export const crew = [
  {
    id: '1',
    image: '/Crew/Crew1.jpg',
    name: 'Crew Member 1',
    duties: 'Tactic and Trim',
    duty_slugs: ['tactic', 'trim'],
  },
  {
    id: '2',
    image: '/Crew/Crew2.jpg',
    name: 'Crew Member 2',
    duties: 'Helmsman',
    duty_slugs: ['helmsman'],
  },
  {
    id: '3',
    image: '/Crew/Crew3.jpg',
    name: 'Crew Member 3',
    duties: 'Helmsman and Tactic',
    duty_slugs: ['helmsman', 'tactic'],
  },
  {
    id: '4',
    image: '/Crew/Crew4.jpg',
    name: 'Crew Member 4',
    duties: 'Main Helmsman',
    duty_slugs: ['helmsman'],
  },
  {
    id: '5',
    image: '/Crew/Crew5.jpg',
    name: 'Crew Member 5',
    duties: 'Helmsman and Trim',
    duty_slugs: ['helmsman', 'trim'],
  },
  {
    id: '6',
    image: '/Crew/Crew6.jpg',
    name: 'Crew Member 6',
    duties: 'Trim',
    duty_slugs: ['trim'],
  },
  {
    id: '7',
    image: '/Crew/Crew7.jpg',
    name: 'Crew Member 7',
    duties: 'Tactic and Trim',
    duty_slugs: ['tactic', 'trim'],
  },
  {
    id: '8',
    image: '/Crew/Crew8.jpg',
    name: 'Crew Member 8',
    duties: 'Helmsman and Trim',
    duty_slugs: ['helmsman', 'trim'],
  },
  {
    id: '9',
    image: '/Crew/Crew9.jpg',
    name: 'Crew Member 9',
    duties: 'Junior Helmsman',
    duty_slugs: ['helmsman'],
  },
  {
    id: '10',
    image: '/Crew/Crew10.jpg',
    name: 'Crew Member 10',
    duties: 'Tactic and Trim',
    duty_slugs: ['tactic', 'trim'],
  },
  {
    id: '11',
    image: '/Crew/Crew11.jpg',
    name: 'Crew Member 11',
    duties: 'Senior Helmsman and Trim',
    duty_slugs: ['helmsman', 'trim'],
  },
  {
    id: '12',
    image: '/Crew/Crew12.jpg',
    name: 'Crew Member 12',
    duties: 'Tactic',
    duty_slugs: ['tactic'],
  },
  {
    id: '13',
    image: '/Crew/Crew13.jpg',
    name: 'Crew Member 13',
    duties: 'Trim',
    duty_slugs: ['trim'],
  },
  {
    id: '14',
    image: '/Crew/Crew14.jpg',
    name: 'Crew Member 14',
    duties: 'Tactic and Trim',
    duty_slugs: ['tactic', 'trim'],
  },
  {
    id: '15',
    image: '/Crew/Crew14.jpg',
    name: 'Crew Member 15',
    duties: 'Tactic',
    duty_slugs: ['tactic'],
  },
];
